export const JUICY_MANGO = 'Juicy Mango'
export const JUICY_MANGO_SUBHEADING = 'Helping humanity invest in long lasting, quality clothing'
export const FEEDBACK_FORM = 'https://forms.gle/1UimSA6g1MPYK7bSA'
export const BUG_FORM = 'https://forms.gle/ruV87xTX3TeHd6UF8'
export const FE_REPO = 'https://github.com/guopher/clothes-fe'
export const BE_REPO = 'https://github.com/guopher/clothes-be'
